# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

use_frameworks! :linkage => :static
$FirebaseSDKVersion = '11.11.0'

pod 'Firebase', '11.11.0', :modular_headers => true
pod 'FirebaseCoreInternal', '11.11.0', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', '11.11.0', :modular_headers => true
pod 'Firebase/Auth', '11.11.0', :modular_headers => true
pod 'Firebase/Firestore', '11.11.0', :modular_headers => true
pod 'Firebase/Messaging', '11.11.0', :modular_headers => true
pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
pod 'RNScreens', :path => '../node_modules/react-native-screens'
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

target 'DriveXProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
